name: bybit
description: (Unofficial) Dart library to communicate with the bybit API over REST or WebSockets
version: 1.4.1
homepage: https://github.com/PimpMyPizza/bybit-dart
repository: https://github.com/PimpMyPizza/bybit-dart
issue_tracker: https://github.com/PimpMyPizza/bybit-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  web_socket_channel: ^2.0.0
  crypto: ^3.0.0
  logger: ^1.0.0-nullsafety.0
  http: ^0.13.0
  sortedmap: ^0.5.0-nullsafety.0
  meta: ^1.3.0
  async: ^2.5.0

dev_dependencies:
  test: ^1.16.7
  pedantic: ^1.11.0